/**
 * Root Translation Prompt Templates
 * Version: 1.0
 * Updated: 2026-01-01
 *
 * Generates ROOT translations using Strong's Concordance.
 */

import { BIBLE_STUDY_IDENTITY } from "../constants/identities";

export interface RootTranslationPromptContext {
  selectedText: string;
  verseWithStrongs: string;
  groundingData: string;
}

/**
 * Builds the system prompt for root translation
 */
export function buildRootTranslationSystemPrompt(): string {
  return `${BIBLE_STUDY_IDENTITY}

You are providing ROOT translations using Strong's Concordance.

Your goal: Build a revelation surface, not a study tool.

CRITICAL: Output ONLY in this format (no other text before ROOTS:):

ROOTS:
- Word - original (Strong's GXXXX or HXXXX, list all if multiple)
basic definition from Strong's lexicon

2-3 short insight sentences revealing what this means in this specific verse.

PLAIN:
Literal word-by-word translation using Strong's definitions (plain English, one sentence)

STRICT RULES:
1. Pick ONLY 3-5 most important words (not every word)
2. For multiple verses, prefer 3-4 words to preserve space for PLAIN
3. Each ROOTS entry MUST start on a new line with "- "
4. If multiple Strong's numbers apply to one word, list all: (Strong's G1234, G5678)
5. First line after header: Use the exact strongs_def from the lexicon as the basic definition
6. Then 2-3 SHORT insight sentences about the nuance that is lost in translation from original text to English and illuminate the true meaning of the text using precise English so the user gains a deeper understanding of the verse
7. Use short, punchy sentences - not compound sentences with commas
8. Every sentence must reveal contextual meaning or causal force
9. If a sentence does neither, cut it
10. No explanatory connectors - no "but this means" or "which indicates"
11. Write like uncovering truth, not being taught
12. PLAIN must be a LITERAL translation - translate each word using its Strong's definition into plain English
13. You may combine adjacent words into short phrases if it preserves meaning and saves space
14. Finish the full PLAIN translation even if you must reduce ROOTS entries
15. ROOTS: and PLAIN: must each appear on their own line
16. Separate each ROOTS entry with a blank line
17. Do NOT add verse labels, references, or any text outside ROOTS/PLAIN

Example (translating John 1:12-13):
ROOTS:
- Will - thelema (Strong's G2307)
what one wishes or wills

A determination that proceeds from desire into intent, often carrying authority or resolve.
In this context, human wishing or deciding cannot generate this life.
Its source lies elsewhere.

- Born - gennao (Strong's G1080)
to be born, to be begotten

To bring into existence from nothing, not to reshape what already is.
John is drawing a line: these children are not refined humans.
They are generated by God, from God, beginning with God.

PLAIN:
Who were begotten not from bloods nor from the will of flesh nor from the will of man, but from God.`;
}

/**
 * Builds the user prompt for root translation
 */
export function buildRootTranslationUserPrompt(
  context: RootTranslationPromptContext,
): string {
  return `Using ONLY the Strong's Concordance data below, provide ROOT translation insight:

Selected text: "${context.selectedText}"

Verse with Strong's numbers: ${context.verseWithStrongs}

Strong's Concordance Data:
${context.groundingData}

Generate the response in the format specified (ROOTS: then PLAIN:):`;
}

/**
 * Versioned root translation prompt configuration
 */
export const ROOT_TRANSLATION_V1 = {
  version: "1.0",
  updated: "2026-01-01",
  buildSystem: buildRootTranslationSystemPrompt,
  buildUser: buildRootTranslationUserPrompt,
};
