import { StyleSheet } from "react-native";
import { MOBILE_TOKENS } from "./tokens";

export const T = MOBILE_TOKENS;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: T.colors.canvas,
  },
  appBackground: {
    flex: 1,
    backgroundColor: T.colors.canvas,
  },
  backdropBlobA: {
    position: "absolute",
    top: -80,
    right: -50,
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: T.colors.accentSoft,
    opacity: 0.8,
  },
  backdropBlobB: {
    position: "absolute",
    bottom: 60,
    left: -70,
    width: 240,
    height: 240,
    borderRadius: 240,
    backgroundColor: T.colors.pineSoft,
    opacity: 0.9,
  },
  rootScrollContent: {
    flexGrow: 1,
    padding: T.spacing.lg,
    paddingBottom: T.spacing.xxl,
  },
  rootFrame: {
    gap: T.spacing.md,
  },
  authHeroPanel: {
    backgroundColor: T.colors.surface,
    borderRadius: T.radius.lg,
    borderWidth: 1,
    borderColor: T.colors.border,
    padding: T.spacing.lg,
    gap: T.spacing.sm,
  },
  globalBusyOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(9, 9, 11, 0.45)",
  },
  panel: {
    backgroundColor: T.colors.surfaceRaised,
    borderRadius: T.radius.lg,
    borderWidth: 1,
    borderColor: T.colors.border,
    padding: T.spacing.lg,
    gap: T.spacing.sm,
    shadowColor: T.colors.shadow,
    shadowOpacity: 0.8,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  panelTitle: {
    color: T.colors.text,
    fontSize: T.typography.heading,
    fontWeight: "700",
  },
  panelSubtitle: {
    color: T.colors.textMuted,
    fontSize: T.typography.body,
    lineHeight: 20,
  },
  input: {
    backgroundColor: T.colors.surface,
    borderColor: T.colors.border,
    borderWidth: 1,
    borderRadius: T.radius.md,
    paddingHorizontal: T.spacing.md,
    paddingVertical: T.spacing.md,
    color: T.colors.text,
    fontSize: T.typography.body,
  },
  fieldLabel: {
    color: T.colors.text,
    fontSize: T.typography.caption,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  fieldGroup: {
    gap: T.spacing.xs,
  },
  helperText: {
    color: T.colors.textMuted,
    fontSize: T.typography.caption,
    lineHeight: 17,
  },
  textAreaInput: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  textAreaInputSmall: {
    minHeight: 68,
    textAlignVertical: "top",
  },
  inputCompact: {
    width: 110,
  },
  row: {
    flexDirection: "row",
    gap: T.spacing.sm,
  },
  rowStack: {
    flexDirection: "column",
  },
  rowAlignCenter: {
    flexDirection: "row",
    alignItems: "center",
    gap: T.spacing.sm,
  },
  spaceBetweenRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: T.spacing.sm,
  },
  flex1: {
    flex: 1,
  },
  providerButton: {
    flex: 1,
    borderRadius: T.radius.md,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  googleButton: {
    backgroundColor: T.colors.surface,
    borderColor: T.colors.border,
  },
  appleButton: {
    backgroundColor: T.colors.ink,
    borderColor: T.colors.border,
  },
  providerButtonLabel: {
    color: T.colors.text,
    fontWeight: "700",
    fontSize: T.typography.body,
  },
  providerButtonLabelInverse: {
    color: T.colors.text,
  },
  primaryButton: {
    flex: 1,
    borderRadius: T.radius.md,
    borderWidth: 1,
    borderColor: T.colors.accent,
    backgroundColor: T.colors.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: T.spacing.md,
  },
  primaryButtonLabel: {
    color: T.colors.ink,
    fontWeight: "700",
    fontSize: T.typography.body,
  },
  secondaryButton: {
    flex: 1,
    borderRadius: T.radius.md,
    borderWidth: 1,
    borderColor: T.colors.border,
    backgroundColor: T.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: T.spacing.md,
  },
  secondaryButtonLabel: {
    color: T.colors.text,
    fontWeight: "700",
    fontSize: T.typography.body,
  },
  ghostButton: {
    borderRadius: T.radius.md,
    borderColor: T.colors.border,
    borderWidth: 1,
    backgroundColor: T.colors.surfaceRaised,
    paddingHorizontal: T.spacing.md,
    paddingVertical: 10,
  },
  ghostButtonLabel: {
    color: T.colors.text,
    fontWeight: "600",
    fontSize: T.typography.body,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  calloutMuted: {
    backgroundColor: T.colors.canvasMuted,
    borderRadius: T.radius.md,
    padding: T.spacing.sm,
  },
  authDividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: T.spacing.sm,
    marginTop: 2,
    marginBottom: 2,
  },
  authDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: T.colors.border,
  },
  authDividerLabel: {
    color: T.colors.textMuted,
    fontSize: T.typography.caption,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  calloutMutedText: {
    color: T.colors.textMuted,
    fontSize: T.typography.caption,
  },
  errorCard: {
    backgroundColor: T.colors.dangerSoft,
    borderRadius: T.radius.md,
    borderWidth: 1,
    borderColor: T.colors.danger,
    paddingHorizontal: T.spacing.sm,
    paddingVertical: T.spacing.sm,
  },
  errorCardText: {
    color: T.colors.danger,
    fontSize: T.typography.body,
  },
  infoCard: {
    backgroundColor: T.colors.pineSoft,
    borderRadius: T.radius.md,
    borderWidth: 1,
    borderColor: T.colors.pine,
    paddingHorizontal: T.spacing.sm,
    paddingVertical: T.spacing.sm,
  },
  infoCardText: {
    color: T.colors.pine,
    fontSize: T.typography.body,
  },
  error: {
    color: T.colors.danger,
    fontSize: T.typography.body,
  },
  info: {
    color: T.colors.pine,
    fontSize: T.typography.body,
  },
  meta: {
    color: T.colors.textMuted,
    fontSize: T.typography.body,
  },
  caption: {
    color: T.colors.textMuted,
    fontSize: T.typography.caption,
  },
  tabContent: {
    gap: T.spacing.md,
    padding: T.spacing.lg,
    paddingBottom: T.spacing.xl,
  },
  routeScrollContent: {
    gap: T.spacing.md,
    padding: T.spacing.lg,
    paddingBottom: T.spacing.xl,
  },
  tabScreen: {
    flex: 1,
    gap: T.spacing.md,
    padding: T.spacing.lg,
    paddingBottom: T.spacing.sm,
  },
  heroCard: {
    backgroundColor: T.colors.surface,
    borderWidth: 1,
    borderColor: T.colors.border,
    borderRadius: T.radius.lg,
    padding: T.spacing.lg,
    gap: T.spacing.sm,
  },
  heroEyebrow: {
    color: T.colors.accent,
    fontSize: T.typography.caption,
    textTransform: "uppercase",
    letterSpacing: 1,
    fontWeight: "700",
  },
  heroTitle: {
    color: T.colors.text,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
  },
  heroSubtitle: {
    color: T.colors.textMuted,
    fontSize: T.typography.body,
    lineHeight: 20,
  },
  statGrid: {
    flexDirection: "row",
    gap: T.spacing.sm,
  },
  statCard: {
    flex: 1,
    borderRadius: T.radius.md,
    backgroundColor: T.colors.surface,
    borderWidth: 1,
    borderColor: T.colors.border,
    padding: T.spacing.sm,
    gap: 4,
  },
  statLabel: {
    color: T.colors.textMuted,
    fontSize: T.typography.caption,
  },
  statValue: {
    color: T.colors.text,
    fontSize: 22,
    fontWeight: "800",
  },
  listContent: {
    gap: T.spacing.md,
    paddingBottom: T.spacing.xl,
  },
  featureCard: {
    backgroundColor: T.colors.surfaceRaised,
    borderRadius: T.radius.lg,
    borderWidth: 1,
    borderColor: T.colors.border,
    padding: T.spacing.lg,
    gap: T.spacing.sm,
  },
  featureCardSelected: {
    borderColor: T.colors.accent,
    backgroundColor: T.colors.accentSoft,
  },
  connectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: T.spacing.sm,
  },
  connectionRoute: {
    flex: 1,
    color: T.colors.text,
    fontSize: 15,
    fontWeight: "700",
  },
  connectionType: {
    color: T.colors.pine,
    backgroundColor: T.colors.pineSoft,
    paddingHorizontal: T.spacing.sm,
    paddingVertical: 4,
    borderRadius: T.radius.pill,
    fontSize: T.typography.caption,
    overflow: "hidden",
  },
  bookmarkText: {
    color: T.colors.text,
    fontSize: T.typography.body,
    lineHeight: 20,
  },
  highlightColorBadgeWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: T.spacing.xs,
    backgroundColor: T.colors.canvasMuted,
    borderRadius: T.radius.pill,
    paddingHorizontal: T.spacing.sm,
    paddingVertical: 4,
    maxWidth: 132,
  },
  highlightColorDot: {
    width: 10,
    height: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.colors.border,
  },
  highlightColorCode: {
    color: T.colors.textMuted,
    fontSize: T.typography.caption,
    flexShrink: 1,
  },
  connectionSynopsis: {
    color: T.colors.text,
    fontSize: T.typography.body,
    lineHeight: 20,
  },
  connectionMetaWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: T.spacing.xs,
  },
  metaPill: {
    color: T.colors.textMuted,
    backgroundColor: T.colors.canvasMuted,
    borderRadius: T.radius.pill,
    paddingHorizontal: T.spacing.sm,
    paddingVertical: 4,
    fontSize: T.typography.caption,
    overflow: "hidden",
  },
  connectionNote: {
    color: T.colors.textMuted,
    fontSize: T.typography.body,
    fontStyle: "italic",
  },
  connectionTimestamp: {
    color: T.colors.textMuted,
    fontSize: T.typography.caption,
  },
  emptyState: {
    backgroundColor: T.colors.surfaceRaised,
    borderRadius: T.radius.lg,
    borderWidth: 1,
    borderColor: T.colors.border,
    padding: T.spacing.xl,
    alignItems: "center",
    gap: T.spacing.sm,
  },
  emptyTitle: {
    color: T.colors.text,
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  emptySubtitle: {
    color: T.colors.textMuted,
    fontSize: T.typography.body,
    textAlign: "center",
    lineHeight: 20,
  },
  listHintRow: {
    paddingHorizontal: T.spacing.xs,
  },
  suggestionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: T.spacing.xs,
  },
  suggestionChip: {
    borderRadius: T.radius.pill,
    borderWidth: 1,
    borderColor: T.colors.border,
    backgroundColor: T.colors.canvasMuted,
    paddingHorizontal: T.spacing.sm,
    paddingVertical: 6,
  },
  suggestionChipLabel: {
    color: T.colors.text,
    fontSize: T.typography.caption,
    fontWeight: "600",
  },
  outlineChip: {
    borderRadius: T.radius.pill,
    borderWidth: 1,
    borderColor: T.colors.border,
    backgroundColor: T.colors.surface,
    paddingHorizontal: T.spacing.sm,
    paddingVertical: 7,
  },
  outlineChipActive: {
    borderColor: T.colors.accent,
    backgroundColor: T.colors.accentSoft,
  },
  outlineChipLabel: {
    color: T.colors.text,
    fontSize: T.typography.caption,
    fontWeight: "700",
  },
  colorPreviewWrap: {
    minWidth: 92,
    borderRadius: T.radius.md,
    borderWidth: 1,
    borderColor: T.colors.border,
    backgroundColor: T.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: T.spacing.sm,
    paddingVertical: 8,
  },
  colorPreviewDot: {
    width: 18,
    height: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.colors.border,
  },
  colorChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: T.spacing.xs,
  },
  colorChip: {
    width: 30,
    height: 30,
    borderRadius: T.radius.pill,
    borderWidth: 1,
    borderColor: T.colors.border,
  },
  colorChipActive: {
    borderColor: T.colors.accentStrong,
    borderWidth: 2,
  },
  dangerButton: {
    flex: 1,
    borderRadius: T.radius.md,
    borderWidth: 1,
    borderColor: T.colors.danger,
    backgroundColor: T.colors.dangerSoft,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: T.spacing.md,
  },
  dangerButtonLabel: {
    color: T.colors.danger,
    fontWeight: "700",
    fontSize: T.typography.body,
  },
});
