/**
 * KJV Book Names and Abbreviations
 */

export const BOOK_NAMES: Record<string, string> = {
  gn: "Genesis",
  ex: "Exodus",
  lv: "Leviticus",
  nu: "Numbers",
  dt: "Deuteronomy",
  js: "Joshua",
  jg: "Judges",
  ru: "Ruth",
  "1sm": "1 Samuel",
  "2sm": "2 Samuel",
  "1ki": "1 Kings",
  "2ki": "2 Kings",
  "1ch": "1 Chronicles",
  "2ch": "2 Chronicles",
  er: "Ezra",
  ne: "Nehemiah",
  es: "Esther",
  jb: "Job",
  ps: "Psalms",
  pr: "Proverbs",
  ec: "Ecclesiastes",
  so: "Song of Solomon",
  is: "Isaiah",
  jr: "Jeremiah",
  lm: "Lamentations",
  ek: "Ezekiel",
  dn: "Daniel",
  hs: "Hosea",
  jl: "Joel",
  am: "Amos",
  ob: "Obadiah",
  jn: "Jonah",
  mi: "Micah",
  na: "Nahum",
  hk: "Habakkuk",
  zp: "Zephaniah",
  hg: "Haggai",
  zc: "Zechariah",
  ml: "Malachi",
  mt: "Matthew",
  mk: "Mark",
  lk: "Luke",
  jo: "John",
  ac: "Acts",
  ro: "Romans",
  "1co": "1 Corinthians",
  "2co": "2 Corinthians",
  gl: "Galatians",
  ep: "Ephesians",
  pp: "Philippians",
  cl: "Colossians",
  "1th": "1 Thessalonians",
  "2th": "2 Thessalonians",
  "1tm": "1 Timothy",
  "2tm": "2 Timothy",
  ti: "Titus",
  pm: "Philemon",
  hb: "Hebrews",
  jm: "James",
  "1pe": "1 Peter",
  "2pe": "2 Peter",
  "1jn": "1 John",
  "2jn": "2 John",
  "3jn": "3 John",
  jd: "Jude",
  rv: "Revelation",
};

export const ABBREV_TO_INDEX: Record<string, number> = {
  gn: 0,
  ex: 1,
  lv: 2,
  nu: 3,
  dt: 4,
  js: 5,
  jg: 6,
  ru: 7,
  "1sm": 8,
  "2sm": 9,
  "1ki": 10,
  "2ki": 11,
  "1ch": 12,
  "2ch": 13,
  er: 14,
  ne: 15,
  es: 16,
  jb: 17,
  ps: 18,
  pr: 19,
  ec: 20,
  so: 21,
  is: 22,
  jr: 23,
  lm: 24,
  ek: 25,
  dn: 26,
  hs: 27,
  jl: 28,
  am: 29,
  ob: 30,
  jn: 31,
  mi: 32,
  na: 33,
  hk: 34,
  zp: 35,
  hg: 36,
  zc: 37,
  ml: 38,
  mt: 39,
  mk: 40,
  lk: 41,
  jo: 42,
  ac: 43,
  ro: 44,
  "1co": 45,
  "2co": 46,
  gl: 47,
  ep: 48,
  pp: 49,
  cl: 50,
  "1th": 51,
  "2th": 52,
  "1tm": 53,
  "2tm": 54,
  ti: 55,
  pm: 56,
  hb: 57,
  jm: 58,
  "1pe": 59,
  "2pe": 60,
  "1jn": 61,
  "2jn": 62,
  "3jn": 63,
  jd: 64,
  rv: 65,
};
