/**
 * KJV Book Names and Abbreviations
 *
 * NOTE: These must match the actual book_abbrev values in the Supabase database!
 * Database abbreviations were verified on 2025-12-05.
 */

export const BOOK_NAMES: Record<string, string> = {
  gn: "Genesis",
  ex: "Exodus",
  lv: "Leviticus",
  nm: "Numbers",
  dt: "Deuteronomy",
  js: "Joshua",
  jud: "Judges",
  rt: "Ruth",
  "1sm": "1 Samuel",
  "2sm": "2 Samuel",
  "1kgs": "1 Kings",
  "2kgs": "2 Kings",
  "1ch": "1 Chronicles",
  "2ch": "2 Chronicles",
  ezr: "Ezra",
  ne: "Nehemiah",
  et: "Esther",
  job: "Job",
  ps: "Psalms",
  prv: "Proverbs",
  ec: "Ecclesiastes",
  so: "Song of Solomon",
  is: "Isaiah",
  jr: "Jeremiah",
  lm: "Lamentations",
  ez: "Ezekiel",
  dn: "Daniel",
  ho: "Hosea",
  jl: "Joel",
  am: "Amos",
  ob: "Obadiah",
  jo: "Jonah", // Database has "jo" for Jonah, not "jn"
  mi: "Micah",
  na: "Nahum",
  hk: "Habakkuk",
  zp: "Zephaniah",
  hg: "Haggai",
  zc: "Zechariah",
  ml: "Malachi",
  mt: "Matthew",
  mk: "Mark",
  lk: "Luke",
  jn: "John", // Database has "jn" for John (Gospel), not "jo"
  act: "Acts",
  rm: "Romans",
  "1co": "1 Corinthians",
  "2co": "2 Corinthians",
  gl: "Galatians",
  eph: "Ephesians",
  ph: "Philippians",
  cl: "Colossians",
  "1ts": "1 Thessalonians",
  "2ts": "2 Thessalonians",
  "1tm": "1 Timothy",
  "2tm": "2 Timothy",
  tt: "Titus",
  phm: "Philemon",
  hb: "Hebrews",
  jm: "James",
  "1pe": "1 Peter",
  "2pe": "2 Peter",
  "1jo": "1 John",
  "2jo": "2 John",
  "3jo": "3 John",
  jd: "Jude",
  re: "Revelation",
};

export const ABBREV_TO_INDEX: Record<string, number> = {
  gn: 0,
  ex: 1,
  lv: 2,
  nm: 3,
  dt: 4,
  js: 5,
  jud: 6,
  rt: 7,
  "1sm": 8,
  "2sm": 9,
  "1kgs": 10,
  "2kgs": 11,
  "1ch": 12,
  "2ch": 13,
  ezr: 14,
  ne: 15,
  et: 16,
  job: 17,
  ps: 18,
  prv: 19,
  ec: 20,
  so: 21,
  is: 22,
  jr: 23,
  lm: 24,
  ez: 25,
  dn: 26,
  ho: 27,
  jl: 28,
  am: 29,
  ob: 30,
  jo: 31, // Jonah
  mi: 32,
  na: 33,
  hk: 34,
  zp: 35,
  hg: 36,
  zc: 37,
  ml: 38,
  mt: 39,
  mk: 40,
  lk: 41,
  jn: 42, // John
  act: 43,
  rm: 44,
  "1co": 45,
  "2co": 46,
  gl: 47,
  eph: 48,
  ph: 49,
  cl: 50,
  "1ts": 51,
  "2ts": 52,
  "1tm": 53,
  "2tm": 54,
  tt: 55,
  phm: 56,
  hb: 57,
  jm: 58,
  "1pe": 59,
  "2pe": 60,
  "1jo": 61,
  "2jo": 62,
  "3jo": 63,
  jd: 64,
  re: 65,
};
